apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: scared-cricket-nodejs 
  janus-idp.io/tekton: scared-cricket-nodejs
  backstage.io/kubernetes-id: scared-cricket-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: scared-cricket-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  